# Generated by Django 4.1.7 on 2023-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menuitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='right',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
