# Generated by Django 4.1.7 on 2023-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menuitem_left_menuitem_level_menuitem_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
