# Generated by Django 4.1.7 on 2023-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_menuitem_parent_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent_right',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
