# Generated by Django 4.1.7 on 2023-02-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_menuitem_parent_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent_left',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent_right',
        ),
    ]
